### ISSUE TITLE
cannot execute

### ISSUE THREAD

**Issue by nnzs9248** [JunHeum/BMBC#3]
Nice work!
Follow the steps you provided to install the environment, but there are such problems:
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import torchvision.transforms.functional as TF
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "D:\Anaconda3\envs\BMBC\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: The specified module was not found。

**Comment by JunHeum** [comment]
Hi, **nnzs9248**.

Thanks for your interest!

We tested code in Ubuntu 16.04, 18.04 only, but not in Window.

According to my background, if there were no errors until package installation, it is considered a directory or path problem.

I hope that the below link can help you solve the problem.
https://support.pyxll.com/hc/en-gb/articles/360041392893-Error-importing-Python-module-DLL-load-failed
